import { Roboto_Flex } from 'next/font/google';
import React from 'react';
const roboto = Roboto_Flex({ subsets: ['latin'] });

export const metadata = {
    title: 'kargakarga',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                {children}

            </body>
        </html>
    );
}
