import React from 'react';
import "../../styles/globals.css"


export const metadata = {
  title: 'kargakarga',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}

      </body>
    </html>
  )
}
